version: '2'
volumes:
    zabbix-server-conf:
    zabbix-server-scripts:
    zabbix-db-data:
    kibana-plugins:
    esdata2:

services:
  db:
    image: gcavalcante8808/zabbix-db-postgres:4.0.0
    restart: always
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: "zabbix"
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data

  server:
    image: gcavalcante8808/zabbix-server:4.0.0
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zabbix
      DB_PASS: zabbix
      DB_NAME: zabbix
      DB_TYPE: POSTGRESQL
      # REALTIME EVENT EXPORT SUPPORT.
      EVENT_EXPORT_DIR: /data
      EVENT_EXPORT_FILESIZE: 100M
    volumes:
     - zabbix-server-conf:/usr/local/etc/zabbix_server.conf.d
     - zabbix-server-scripts:/usr/local/share/zabbix/external_scripts
     # REALTIME EVENT EXPORT SUPPORT.
     - ./event-data:/data
    ports:
     - "10051:10051"
    depends_on:
     - db
  
  frontend:
    image: gcavalcante8808/zabbix-frontend:4.0.0
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: zabbix
      DB_PASS: zabbix
      DB_NAME: zabbix
      DB_TYPE: POSTGRESQL
      ZBX_SERVER: server
      ZBX_SERVER_PORT: 10051
      ZBX_SERVER_NAME: "Zabbix Docker"
    ports:
      - "80:80"
    depends_on:
     - db

  fluentd:
    image: fluentd:es
    build: ./fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./event-data:/data
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
     - cluster.name=docker-cluster
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms512m -Xmx512m
     - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    restart: always
    networks:
     - default
    ports:
     - 5601:5601
    volumes:
     - kibana-plugins:/usr/share/kibana/plugins